---
# defaults file for win-configure-demo-webserver
iis_test_message: "Provisioned Through CFME"
ansible_connection: winrm
ansible_user: Administrator
ansible_winrm_server_cert_validation: ignore
web_port: 8080
web_dir: C:\wwwroot\ansibledemo